channels:
  - conda-forge
  - bioconda
dependencies:
  - star ==2.7.3a
  - samtools ==1.9
  - samblaster ==0.1.24
  - seqtk ==1.3
  - trimadap ==r11
  # NB: gnuplot 5.2.7 is incompatible with samtools ==1.9
  # see https://github.com/samtools/samtools/issues/1065
  - gnuplot ==5.2.6
  - libpng ==1.6.37
  - inline-html ==1.0.0
