channels:
- bioconda
- conda-forge
- anaconda
dependencies:
- r-base
- r-tidyverse
- bioconductor-annotationdbi
- bioconductor-bsgenome
- bioconductor-genomicranges
- bioconductor-org.hs.eg.db
- bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
- bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
- bioconductor-bsgenome.hsapiens.1000genomes.hs37d5
- bioconductor-bsgenome.hsapiens.ucsc.hg38

